spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: localhost
    port: 8025
    username:
    password:
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 8C45AAD80AEE55465C96EB7C2766DA5B61B8D78176B3266B07386329485B2600
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # a week
  mailing:
    frontend:
      activation-url: http://localhost:3000/activate-account
server:
  port: 8088